import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Fade } from 'react-awesome-reveal'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <Fade direction="down">
        <h1 className="text-3xl font-bold  my-6">
          Hello world!
        </h1>
        </Fade>

    </main>


   
    </div>
  )
}
